### ISSUE TITLE
[dependency error] plugin_platform_interface

### ISSUE THREAD

**Issue by KKimj** [rodydavis/easy_web_view#57]
Hello,
I tried to run example in your repo
Here are errors

```
C:\Users\ziun7\tmp\easy_web_view\example>flutter run -d chrome
Launching lib\main.dart on Chrome in debug mode...
Error: Cannot run with sound null safety, because the following dependencies
don't support null safety:

 - package:plugin_platform_interface

For solutions, see https://dart.dev/go/unsound-null-safety
Unhandled exception:
Bad state: Unsupported Null Safety mode NonNullableByDefaultCompiledMode.Invalid, in null.
#0      ProgramCompiler.emitModule (package:dev_compiler/src/kernel/compiler.dart:439:9)
#1      JavaScriptBundler.compile (package:frontend_server/src/javascript_bundle.dart:146:33)
#2      FrontendCompiler.writeJavascriptBundle (package:frontend_server/frontend_server.dart:638:47)
<asynchronous suspension>
#3      FrontendCompiler.compile (package:frontend_server/frontend_server.dart:549:9)
<asynchronous suspension>
#4      listenAndCompile.<anonymous closure> (package:frontend_server/frontend_server.dart:1119:11)
<asynchronous suspension>
the Dart compiler exited unexpectedly.
Waiting for connection from debug service on Chrome...             22.4s
Failed to compile application.
```

I found at pubspec.lock
```
  plugin_platform_interface:
    dependency: transitive
    description:
      name: plugin_platform_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.3"
```

We should update to 2.0.0

https://pub.dev/packages/plugin_platform_interface/versions

![image](https://user-images.githubusercontent.com/40026920/119262076-e870b380-bc14-11eb-9b22-852901ba4c10.png)
